name: Frontend Manual Triggers
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production
jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ inputs.environment == 'production' && secrets.ABTI_FRONTEND_DEPLOY_TOKEN_PROD || secrets.ABTI_FRONTEND_DEPLOY_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./frontend"
          api_location: ""
          output_location: "dist"
